import Image from "next/image";
import Link from "next/link";
import type { ReactNode } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PageHeading } from "@/components/page-heading";
import { StatusBadge } from "@/components/status-badge";
import { formatShopDateTime, ReportRuleError } from "@/domain/reporting";
import { requirePermission } from "@/lib/auth";
import { reportExportKinds, reportQuerySchema, reportViews, type ReportQuery } from "@/lib/validations/reports";
import { db } from "@/lib/db";
import { getReportData } from "@/server/report-service";
import { ReportActions } from "./report-actions";

const labels: Record<(typeof reportViews)[number], string> = { sales: "Sales", expenses: "Expenses", financial: "Financial", payments: "Payment methods", staff: "Staff activity", outstanding: "Outstanding", orders: "Orders", customers: "Customers", "cash-sessions": "Cash sessions" };
const money = (value: { toFixed(digits: number): string } | string) => `Rs. ${typeof value === "string" ? Number(value).toFixed(2) : value.toFixed(2)}`;

function Table({ headers, rows, empty }: { headers: string[]; rows: ReactNode[][]; empty: string }) {
  return <Card className="report-table overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr>{headers.map((header) => <th className="p-4" key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr className="border-t border-slate-200" key={index}>{row.map((cell, cellIndex) => <td className="p-4 align-top" key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table>{!rows.length ? <p className="p-12 text-center text-slate-500">{empty}</p> : null}</Card>;
}

export default async function ReportsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const user = await requirePermission("reports:view");
  const raw = await searchParams;
  const parsed = reportQuerySchema.safeParse(Object.fromEntries(Object.entries(raw).map(([key, value]) => [key, typeof value === "string" ? value : undefined])));
  const query: ReportQuery = parsed.success ? parsed.data : reportQuerySchema.parse({});
  const validationError = parsed.success ? "" : "The selected report filters are invalid.";
  const reportPromise = validationError
    ? Promise.resolve({ report: null, error: validationError })
    : getReportData(query).then((report) => ({ report, error: "" })).catch((caught) => ({ report: null, error: caught instanceof ReportRuleError ? caught.message : "The report could not be loaded." }));
  const [settings, staff, result] = await Promise.all([db.setting.findUnique({ where: { id: "primary" } }), db.user.findMany({ where: { status: "ACTIVE" }, select: { id: true, name: true }, orderBy: { name: "asc" } }), reportPromise]);
  const { report, error } = result;
  const downloadable = reportExportKinds.includes(query.view as (typeof reportExportKinds)[number]);
  const exportParams = new URLSearchParams(); for (const [key, value] of Object.entries(query)) if (key !== "view" && value) exportParams.set(key, value);
  const download = downloadable ? `/reports/export/${query.view}?${exportParams}` : undefined;
  return <div className="report-page"><style>{`@page report { size: A4 landscape; margin: 12mm; } @media print { .report-page { page: report; width: 100%; color: #0f172a; } .report-page .report-table { box-shadow: none; border: 1px solid #cbd5e1; } .report-page table { min-width: 0 !important; font-size: 9px; } .report-page th, .report-page td { padding: 6px !important; } .report-page tr { break-inside: avoid; } .report-page .report-print-header { display: flex !important; margin-bottom: 16px; gap: 12px; align-items: center; border-bottom: 2px solid #0f172a; padding-bottom: 10px; } }`}</style><div className="print:hidden"><PageHeading eyebrow="Management" title="Reports" description="Operational reporting from finalized source records. Operational net income is sales less expenses." action={report ? <ReportActions downloadUrl={download} /> : undefined} /></div>
    <div className="report-print-header hidden print:flex"><Image src="/brand/startek-logo.png" alt="Startek Print Hub" width={62} height={62} /><div><p className="text-xl font-black">{settings?.businessName ?? "Startek Print Hub"}</p><p className="text-sm">{settings?.address ?? "No.62 Padukka Road, Meegoda"} · {settings?.phonePrimary ?? "0705935320"} / {settings?.phoneSecond ?? "0777250493"} · {settings?.email ?? "startekprinthub@gmail.com"}</p><p className="mt-1 text-sm font-bold">{labels[query.view]} report · {report?.range.label}</p><p className="text-xs">Generated {formatShopDateTime(new Date())} by {user.name}</p></div></div>
    <nav aria-label="Report types" className="mb-5 flex gap-2 overflow-x-auto pb-2 print:hidden">{reportViews.map((view) => <Button key={view} variant={query.view === view ? "default" : "secondary"} asChild><Link href={`/reports?view=${view}&preset=${query.preset}`}>{labels[view]}</Link></Button>)}</nav>
    <Card className="mb-5 p-5 print:hidden"><form className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input type="hidden" name="view" value={query.view} /><select name="preset" defaultValue={query.preset} className="min-h-12 rounded-xl border border-slate-300 bg-white px-4" aria-label="Date preset"><option value="today">Today</option><option value="week">This week (Mon–Sun)</option><option value="month">Month</option><option value="custom">Custom range</option></select><Input type="month" name="month" defaultValue={query.month} aria-label="Selected month" /><Input type="date" name="from" defaultValue={query.from} aria-label="From date" /><Input type="date" name="to" defaultValue={query.to} aria-label="To date" />
      {["sales", "expenses", "payments", "staff", "orders", "cash-sessions"].includes(query.view) ? <select name="staff" defaultValue={query.staff ?? ""} className="min-h-12 rounded-xl border border-slate-300 bg-white px-4" aria-label="Staff"><option value="">All staff</option>{staff.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select> : null}
      {query.view === "expenses" ? <select name="category" defaultValue={query.category ?? ""} className="min-h-12 rounded-xl border border-slate-300 bg-white px-4" aria-label="Expense category"><option value="">All categories</option>{["MATERIALS", "ELECTRICITY", "SALARY", "TRANSPORT", "MAINTENANCE", "RENT", "PETTY_CASH", "OTHER"].map((row) => <option key={row}>{row.replaceAll("_", " ")}</option>)}</select> : null}
      {["expenses", "payments"].includes(query.view) ? <select name="paymentMethod" defaultValue={query.paymentMethod ?? ""} className="min-h-12 rounded-xl border border-slate-300 bg-white px-4" aria-label="Payment method"><option value="">All payment methods</option>{["CASH", "CARD", "BANK_TRANSFER", "QR"].map((row) => <option key={row}>{row.replaceAll("_", " ")}</option>)}</select> : null}
      {query.view === "orders" ? <select name="status" defaultValue={query.status ?? ""} className="min-h-12 rounded-xl border border-slate-300 bg-white px-4" aria-label="Order status"><option value="">All order groups</option>{["PENDING", "READY", "DELIVERED", "CANCELLED", "OVERDUE"].map((row) => <option key={row}>{row}</option>)}</select> : null}
      {query.view === "cash-sessions" ? <select name="status" defaultValue={query.status ?? ""} className="min-h-12 rounded-xl border border-slate-300 bg-white px-4" aria-label="Session status"><option value="">All session statuses</option><option>OPEN</option><option>CLOSED</option></select> : null}
      {["sales", "expenses", "outstanding", "orders", "customers"].includes(query.view) ? <Input name="search" defaultValue={query.search} placeholder="Search report" aria-label="Search report" /> : null}
      {query.view === "outstanding" ? <select name="sort" defaultValue={query.sort} className="min-h-12 rounded-xl border border-slate-300 bg-white px-4" aria-label="Sort outstanding"><option value="largest">Largest outstanding</option><option value="oldest">Oldest invoice</option><option value="newest">Newest invoice</option></select> : null}
      <div className="flex gap-3"><Button className="flex-1">Apply</Button><Button className="flex-1" variant="secondary" asChild><Link href={`/reports?view=${query.view}`}>Reset</Link></Button></div></form><p className="mt-3 text-xs text-slate-500">Dates are inclusive Asia/Colombo shop dates. Month applies when the Month preset is selected; custom requires both dates.</p></Card>
    {error ? <Card className="border-rose-200 bg-rose-50 p-6 text-rose-800"><h2 className="font-black">Unable to load report</h2><p className="mt-1">{error}</p></Card> : null}
    {report ? <><div className={`mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4 ${query.view === "financial" ? "print:hidden" : ""}`}><Summary label={`Sales · ${report.summary.invoiceCount} invoices`} value={money(report.summary.sales)} /><Summary label="Payments received" value={money(report.summary.payments)} /><Summary label={`Expenses · ${report.summary.expenseCount} records`} value={money(report.summary.expenses)} /><Summary label="Operational net" value={money(report.summary.operationalNet)} /></div><p className="mb-4 text-sm font-bold text-slate-500">Reporting period: {report.range.label} · Asia/Colombo</p>
      {query.view === "sales" ? <Table headers={["Invoice", "Date", "Customer", "Cashier", "Total", "Paid", "Outstanding", "Status"]} rows={report.invoices.map((row) => [<Link className="font-black text-blue-700" href={`/invoices/${row.id}`} key="l">{row.invoiceNumber}</Link>, formatShopDateTime(row.createdAt), row.customerNameSnapshot ?? "Walk-in", row.createdBy.name, money(row.grandTotal), money(row.paid), money(row.outstanding), <StatusBadge status={row.status} key="s" />])} empty="No finalized sales in this period." /> : null}
      {query.view === "expenses" ? <><div className="mb-5 grid gap-3 md:grid-cols-4">{report.expenseCategories.filter((row) => Number(row.total)).map((row) => <Summary key={row.category} label={row.category.replaceAll("_", " ")} value={money(row.total)} small />)}</div><Table headers={["Expense", "Date", "Category", "Description", "Method", "Entered by", "Amount", "Status"]} rows={report.expenses.map((row) => [row.expenseNumber, formatShopDateTime(row.expenseDate), row.category.replaceAll("_", " "), row.description, row.paymentMethod.replaceAll("_", " "), row.createdBy.name, money(row.amount), <StatusBadge status={row.status} key="s" />])} empty="No expenses in this period." /></> : null}
      {query.view === "financial" ? <Card className="p-6"><h2 className="text-lg font-black">Operational financial summary</h2><p className="mt-2 text-sm text-slate-500">This is an operational view, not gross profit or an accounting statement. Payments received remain distinct from sales.</p><dl className="mt-6 space-y-4"><Line label={`Sales (${report.summary.invoiceCount} invoices)`} value={money(report.summary.sales)} /><Line label={`Expenses (${report.summary.expenseCount} records)`} value={`− ${money(report.summary.expenses)}`} /><Line label="Operational net income" value={money(report.summary.operationalNet)} strong /><Line label="Payments received" value={money(report.summary.payments)} /><Line label="Outstanding balances" value={money(report.summary.outstanding)} /></dl></Card> : null}
      {query.view === "payments" ? <><div className="mb-5 grid gap-3 md:grid-cols-4">{report.paymentMethods.map((row) => <Summary key={row.method} label={`${row.method.replaceAll("_", " ")} · ${row.count}`} value={money(row.total)} small />)}</div><Table headers={["Date", "Invoice", "Method", "Reference", "Recorded by", "Amount"]} rows={report.payments.map((row) => [formatShopDateTime(row.createdAt), <Link className="font-bold text-blue-700" href={`/invoices/${row.invoice.id}`} key="i">{row.invoice.invoiceNumber}</Link>, row.method.replaceAll("_", " "), row.reference ?? "—", row.recordedBy.name, money(row.amount)])} empty="No valid payments in this period." /></> : null}
      {query.view === "staff" ? <Table headers={["Staff", "Role", "Invoices", "Sales created", "Payments", "Payments recorded", "Expenses", "Register open / close"]} rows={report.staff.map((row) => [row.name, row.role, row.salesCount, money(row.sales), row.paymentCount, money(row.payments), row.expenseCount, `${row.registerOpens} / ${row.registerCloses}`])} empty="No staff activity in this period." /> : null}
      {query.view === "outstanding" ? <Table headers={["Invoice", "Date", "Customer", "Phone", "Created by", "Total", "Paid", "Outstanding"]} rows={report.outstanding.map((row) => [<Link className="font-black text-blue-700" href={`/invoices/${row.id}`} key="i">{row.invoiceNumber}</Link>, formatShopDateTime(row.createdAt), row.customerNameSnapshot ?? "Walk-in", row.customerPhoneSnapshot ?? "—", row.createdBy.name, money(row.grandTotal), money(row.paid), <strong className="text-rose-700" key="o">{money(row.outstanding)}</strong>])} empty="No outstanding invoices in this period." /> : null}
      {query.view === "orders" ? <><div className="mb-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(report.orderGroups).map(([group, count]) => <Summary key={group} label={group} value={String(count)} small />)}</div><Table headers={["Order", "Created", "Customer", "Job", "Status / group", "Due", "Assigned", "Invoice", "Paid", "Outstanding"]} rows={report.orders.map((row) => [<Link className="font-black text-blue-700" href={`/orders/${row.id}`} key="o">{row.orderNumber}</Link>, formatShopDateTime(row.createdAt), `${row.customerNameSnapshot} · ${row.customerPhoneSnapshot}`, row.jobName ?? "—", <div key="s"><StatusBadge status={row.status} />{row.overdue ? <p className="mt-1 text-xs font-black text-rose-700">OVERDUE</p> : null}</div>, row.dueDate?.toISOString().slice(0, 10) ?? "—", row.assignedStaff?.name ?? "Unassigned", row.invoice ? <Link className="text-blue-700" href={`/invoices/${row.invoice.id}`} key="i">{row.invoice.invoiceNumber}</Link> : "—", row.paid ? money(row.paid) : "—", row.outstanding ? money(row.outstanding) : "—"]) } empty="No orders created in this period." /></> : null}
      {query.view === "customers" ? <><Table headers={["Customer", "Phone", "Invoices", "Total invoiced", "Total paid", "Outstanding"]} rows={report.customers.map((row) => [row.name, row.phone, row.invoiceCount, money(row.sales), money(row.paid), money(row.outstanding)])} empty="No customer sales in this period." />{query.search ? <div className="mt-5"><h2 className="mb-3 text-lg font-black">Matching invoice history</h2><Table headers={["Invoice", "Date", "Customer", "Total", "Paid", "Outstanding"]} rows={report.invoices.map((row) => [<Link href={`/invoices/${row.id}`} className="font-black text-blue-700" key="i">{row.invoiceNumber}</Link>, formatShopDateTime(row.createdAt), row.customerNameSnapshot ?? "Walk-in", money(row.grandTotal), money(row.paid), money(row.outstanding)])} empty="No invoice history matches this customer search." /></div> : null}</> : null}
      {query.view === "cash-sessions" ? <Table headers={["Opened / staff", "Closed / staff", "Opening", "Receipts", "Expenses", "Deposits", "Withdrawals", "Expected", "Actual", "Difference", "Status"]} rows={report.cashSessions.map((row) => [<span key="o">{formatShopDateTime(row.openedAt)}<br />{row.openedBy.name}</span>, row.closedAt ? <span key="c">{formatShopDateTime(row.closedAt)}<br />{row.closedBy?.name ?? "—"}</span> : "—", money(row.openingCash), money(row.cashReceipts), money(row.cashExpenses), money(row.deposits), money(row.withdrawals), row.expectedCash ? money(row.expectedCash) : "—", row.actualCash ? money(row.actualCash) : "—", row.difference ? money(row.difference) : "—", <StatusBadge status={row.status} key="s" />])} empty="No cash sessions opened in this period." /> : null}
    </> : null}
  </div>;
}

function Summary({ label, value, small = false }: { label: string; value: string; small?: boolean }) { return <Card className={small ? "p-4" : "p-5"}><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className={`${small ? "text-xl" : "text-2xl"} mt-2 font-black text-slate-950`}>{value}</p></Card>; }
function Line({ label, value, strong = false }: { label: string; value: string; strong?: boolean }) { return <div className={`flex justify-between border-b pb-3 ${strong ? "text-lg font-black" : "font-bold"}`}><dt>{label}</dt><dd>{value}</dd></div>; }
