"use client";
import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Plus, Search, Trash2 } from "lucide-react";
import { calculateInvoiceTotals } from "@/domain/financial";
import { lookupQuotationCustomer, saveQuotation, updateQuotation } from "@/app/(workspace)/phase4-actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Row = { description: string; quantity: string; unitPrice: string };
type Initial = { id: string; customerName: string; customerPhone: string; discount: string; notes: string; validUntil: string; items: Row[] };
export function QuotationForm({ initial }: { initial?: Initial }) {
  const router = useRouter(); const [pending, start] = useTransition(); const [message, setMessage] = useState("");
  const [name, setName] = useState(initial?.customerName ?? ""); const [phone, setPhone] = useState(initial?.customerPhone ?? ""); const [discount, setDiscount] = useState(initial?.discount ?? "0.00"); const [notes, setNotes] = useState(initial?.notes ?? ""); const [validUntil, setValidUntil] = useState(initial?.validUntil ?? ""); const [rows, setRows] = useState<Row[]>(initial?.items ?? [{ description: "", quantity: "1", unitPrice: "0.00" }]);
  const totals = useMemo(() => { try { return calculateInvoiceTotals(rows.map((r) => ({ quantity: r.quantity || "0", unitPrice: r.unitPrice || "0" })), discount || "0"); } catch { return null; } }, [rows, discount]);
  function patch(i: number, key: keyof Row, value: string) { setRows((current) => current.map((r, x) => x === i ? { ...r, [key]: value } : r)); }
  function submit(issueNow: boolean) { start(async () => { setMessage(""); const common = { customerName: name, customerPhone: phone, discount, notes, validUntil, items: rows }; const result = initial ? await updateQuotation({ quotationId: initial.id, ...common }) : await saveQuotation({ idempotencyKey: crypto.randomUUID(), issueNow, ...common }); if (result.error) setMessage(result.error); else router.push(`/quotations/${result.data?.id ?? initial?.id}`); }); }
  function lookup() { start(async () => { const customer = await lookupQuotationCustomer(phone); if (customer) { setName(customer.name); setMessage("Existing customer loaded"); } else setMessage("No existing customer found; a customer will be created when saved."); }); }
  return <div className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black">Customer</h2><div className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Customer name" /><Input value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="0771234567" inputMode="tel" /><Button type="button" variant="secondary" onClick={lookup} disabled={pending}><Search className="size-5" /> Lookup</Button></div></section>
  <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-black">Manual quotation items</h2><Button type="button" variant="secondary" onClick={() => setRows((r) => [...r, { description: "", quantity: "1", unitPrice: "0.00" }])}><Plus className="size-5" /> Add row</Button></div><div className="mt-4 space-y-3">{rows.map((row, i) => <div key={i} className="grid gap-3 rounded-xl bg-slate-50 p-3 md:grid-cols-[1fr_130px_160px_52px]"><Input value={row.description} onChange={(e) => patch(i, "description", e.target.value)} placeholder="Description" /><Input value={row.quantity} onChange={(e) => patch(i, "quantity", e.target.value)} inputMode="decimal" aria-label="Quantity" /><Input value={row.unitPrice} onChange={(e) => patch(i, "unitPrice", e.target.value)} inputMode="decimal" aria-label="Unit price" /><Button type="button" size="icon" variant="ghost" aria-label="Remove item" disabled={rows.length === 1} onClick={() => setRows((r) => r.filter((_, x) => x !== i))}><Trash2 className="size-5" /></Button></div>)}</div></section>
  <div className="grid gap-5 lg:grid-cols-[1fr_340px]"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black">Terms</h2><div className="mt-4 grid gap-3"><Input type="date" value={validUntil} onChange={(e) => setValidUntil(e.target.value)} aria-label="Valid until" /><textarea value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Notes and terms" className="min-h-28 rounded-xl border border-slate-300 p-4" /></div></section><section className="rounded-2xl bg-slate-900 p-6 text-white"><h2 className="font-black">Totals</h2><div className="mt-4 space-y-3"><Line label="Subtotal" value={totals?.subtotal.toFixed(2) ?? "—"} /><div><label className="text-sm text-slate-300">Discount</label><Input value={discount} onChange={(e) => setDiscount(e.target.value)} inputMode="decimal" className="mt-1 text-slate-950" /></div><Line label="Grand total" value={totals?.grandTotal.toFixed(2) ?? "—"} strong /></div></section></div>
  {message ? <p role="status" className="rounded-xl bg-blue-50 p-4 font-bold text-blue-800">{message}</p> : null}<div className="flex flex-wrap gap-3"><Button type="button" size="lg" disabled={pending} onClick={() => submit(false)}>{initial ? "Save changes" : "Save draft"}</Button>{!initial ? <Button type="button" size="lg" variant="secondary" disabled={pending} onClick={() => submit(true)}>Save and issue</Button> : null}</div></div>;
}
function Line({ label, value, strong }: { label: string; value: string; strong?: boolean }) { return <div className={`flex justify-between ${strong ? "border-t border-white/30 pt-3 text-lg font-black" : "font-bold"}`}><span>{label}</span><span>Rs. {value}</span></div>; }
