"use client";

import { useEffect, useState } from "react";
import { ArchiveRestore, Download, HardDriveDownload, ShieldCheck, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Preview = {
  manifest: {
    applicationVersion: string;
    schemaVersion: string;
    generatedAt: string;
    generatedBy: { name: string; email: string };
    businessName: string;
    recordCounts: Record<string, number>;
    checksum: string;
  };
  warnings: string[];
};

type Props = { lastBackup: { createdAtLabel: string; userName: string | null } | null; applicationVersion: string; schemaVersion: string };

export function BackupRestorePanel({ lastBackup, applicationVersion, schemaVersion }: Props) {
  const [download, setDownload] = useState<{ url: string; filename: string } | null>(null);
  const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState<Preview | null>(null);
  const [confirmation, setConfirmation] = useState("");
  const [busy, setBusy] = useState<"create" | "validate" | "restore" | null>(null);
  const [message, setMessage] = useState<string | null>(null);

  useEffect(() => () => { if (download) URL.revokeObjectURL(download.url); }, [download]);

  async function createBackup() {
    setBusy("create"); setMessage(null);
    try {
      const response = await fetch("/api/backups/create", { method: "POST", cache: "no-store" });
      if (!response.ok) throw new Error("Backup generation failed");
      const disposition = response.headers.get("content-disposition") ?? "";
      const filename = disposition.match(/filename="([^"]+)"/)?.[1] ?? "startek-pos-backup.zip";
      const next = { url: URL.createObjectURL(await response.blob()), filename };
      if (download) URL.revokeObjectURL(download.url);
      setDownload(next); setMessage("Backup generated and ready to download.");
    } catch (error) { setMessage(error instanceof Error ? error.message : "Backup generation failed"); }
    finally { setBusy(null); }
  }

  async function validateBackup() {
    if (!file) return;
    setBusy("validate"); setMessage(null); setPreview(null); setConfirmation("");
    try {
      const form = new FormData(); form.set("backup", file);
      const response = await fetch("/api/backups/preview", { method: "POST", body: form });
      const body = await response.json() as Preview & { error?: string };
      if (!response.ok) throw new Error(body.error ?? "Backup validation failed");
      setPreview(body); setMessage("Checksum, version, record counts, and relationships are valid.");
    } catch (error) { setMessage(error instanceof Error ? error.message : "Backup validation failed"); }
    finally { setBusy(null); }
  }

  async function restoreBackup() {
    if (!file || !preview || confirmation !== "RESTORE DEVELOPMENT") return;
    setBusy("restore"); setMessage(null);
    try {
      const form = new FormData(); form.set("backup", file); form.set("confirmation", confirmation);
      const response = await fetch("/api/backups/restore", { method: "POST", body: form });
      const body = await response.json() as { error?: string };
      if (!response.ok) throw new Error(body.error ?? "Restore failed");
      setMessage("Restore completed and record counts were verified."); setConfirmation("");
    } catch (error) { setMessage(error instanceof Error ? error.message : "Restore failed"); }
    finally { setBusy(null); }
  }

  return <div className="space-y-7">
    <section className="rounded-2xl border border-slate-200 p-5">
      <div className="flex items-start gap-3"><HardDriveDownload className="mt-1 size-6 text-blue-700"/><div><h3 className="font-black text-slate-950">Create portable backup</h3><p className="mt-1 text-sm text-slate-600">Exports business records and audit history. Passwords, sessions, connection strings, and signing keys are excluded.</p></div></div>
      <div className="mt-4 flex flex-wrap gap-3"><Button type="button" onClick={createBackup} disabled={busy !== null}>{busy === "create" ? "Generating…" : "Generate backup"}</Button>{download ? <Button asChild variant="secondary"><a href={download.url} download={download.filename}><Download className="size-5"/>Download ZIP</a></Button> : null}</div>
      <dl className="mt-3 grid gap-1 text-xs text-slate-500"><div><dt className="inline font-bold">Last backup: </dt><dd className="inline">{lastBackup?.createdAtLabel ?? "No backup audit recorded"}</dd></div><div><dt className="inline font-bold">Generated by: </dt><dd className="inline">{lastBackup?.userName ?? "—"}</dd></div><div><dt className="inline font-bold">Application / schema version: </dt><dd className="inline">{applicationVersion} / {schemaVersion}</dd></div></dl>
    </section>

    <section className="rounded-2xl border border-amber-200 bg-amber-50/40 p-5">
      <div className="flex items-start gap-3"><ArchiveRestore className="mt-1 size-6 text-amber-700"/><div><h3 className="font-black text-slate-950">Validate and restore</h3><p className="mt-1 text-sm text-slate-600">Upload first for a read-only preview. Restore is transactional and restricted to an empty DEVELOPMENT business dataset.</p></div></div>
      <label className="mt-4 block text-sm font-bold text-slate-700">Backup ZIP<Input className="mt-2 min-h-12 bg-white" type="file" accept=".zip,application/zip" onChange={(event) => { setFile(event.target.files?.[0] ?? null); setPreview(null); setConfirmation(""); setMessage(null); }}/></label>
      <Button type="button" variant="secondary" className="mt-3" onClick={validateBackup} disabled={!file || busy !== null}><Upload className="size-5"/>{busy === "validate" ? "Validating…" : "Validate backup"}</Button>
      {preview ? <div className="mt-5 rounded-xl border border-emerald-200 bg-white p-4 text-sm">
        <p className="flex items-center gap-2 font-black text-emerald-800"><ShieldCheck className="size-5"/>Validated backup</p>
        <dl className="mt-3 grid gap-2 sm:grid-cols-2"><div><dt className="text-slate-500">Business</dt><dd className="font-bold">{preview.manifest.businessName}</dd></div><div><dt className="text-slate-500">Generated</dt><dd className="font-bold">{new Date(preview.manifest.generatedAt).toLocaleString()}</dd></div><div><dt className="text-slate-500">App / schema</dt><dd className="font-bold">{preview.manifest.applicationVersion} / {preview.manifest.schemaVersion}</dd></div><div><dt className="text-slate-500">Records</dt><dd className="font-bold">{Object.values(preview.manifest.recordCounts).reduce((sum, count) => sum + count, 0)}</dd></div></dl>
        <p className="mt-3 break-all font-mono text-xs text-slate-500">SHA-256: {preview.manifest.checksum}</p>
        <ul className="mt-3 list-disc space-y-1 pl-5 text-amber-800">{preview.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul>
        <label className="mt-4 block font-bold text-slate-700">Type RESTORE DEVELOPMENT to confirm<Input className="mt-2 min-h-12 bg-white" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoComplete="off"/></label>
        <Button type="button" variant="danger" className="mt-3" onClick={restoreBackup} disabled={confirmation !== "RESTORE DEVELOPMENT" || busy !== null}>{busy === "restore" ? "Restoring…" : "Restore validated backup"}</Button>
      </div> : null}
    </section>
    {message ? <p role="status" className="rounded-xl bg-slate-100 p-4 text-sm font-bold text-slate-700">{message}</p> : null}
  </div>;
}
