import "dotenv/config";
import { randomUUID } from "node:crypto";
import { execFileSync } from "node:child_process";
import { afterAll,beforeAll,expect,test,vi } from "vitest";
vi.mock("server-only",()=>({}));
const project="fbnwigknxlapnemmmugd";if(process.env.DATABASE_ENVIRONMENT!=="development")throw new Error("Development environment required");for(const key of ["DATABASE_URL","DIRECT_URL"] as const){const u=new URL(process.env[key]??"");if(u.username!==`postgres.${project}`||u.hostname!=="aws-0-ap-northeast-2.pooler.supabase.com"||u.port!==(key==="DATABASE_URL"?"6543":"5432"))throw new Error("Unapproved integration database")}execFileSync("git",["check-ignore","-q",".env"]);
const{db}=await import("../../src/lib/db");const{createQuotation,changeQuotationStatus,convertQuotation}=await import("../../src/server/quotation-service");const{changeOrderStatus,createInvoiceFromOrder}=await import("../../src/server/order-service");const{addInvoicePayment,getInvoiceById}=await import("../../src/server/invoice-service");const{quotationInputSchema}=await import("../../src/lib/validations/phase4");
let actorId:string;const run=randomUUID();
beforeAll(async()=>{const admin=await db.user.findUniqueOrThrow({where:{email:process.env.SEED_ADMIN_EMAIL!.trim().toLowerCase()}});actorId=admin.id});afterAll(()=>db.$disconnect());
function input(phone:string,discount="500.00"){return quotationInputSchema.parse({idempotencyKey:randomUUID(),customerName:"Sample Print Customer",customerPhone:phone,discount,notes:`Phase 4 integration ${run}`,validUntil:"2099-12-31",issueNow:false,items:[{description:"Business Cards",quantity:"500",unitPrice:"8.00"},{description:"Banner Printing",quantity:"1",unitPrice:"3500.00"}]})}
async function accepted(phone:string){const q=await createQuotation(input(phone),actorId);await changeQuotationStatus(q.id,"ISSUED",null,actorId);await changeQuotationStatus(q.id,"ACCEPTED",null,actorId);return q}

test("quotation calculations, numbering, lifecycle, atomic conversion and duplicate protection",async()=>{const q=await accepted("0775551234");expect(q.quotationNumber).toMatch(/^SPH-QT-\d{6}$/);expect(q.subtotal.toFixed(2)).toBe("7500.00");expect(q.grandTotal.toFixed(2)).toBe("7000.00");const attempts=await Promise.allSettled([convertQuotation({quotationId:q.id,jobName:"Acceptance print job",dueDate:"2099-12-31",assignedStaffId:null,notes:"Integration"},actorId),convertQuotation({quotationId:q.id,jobName:"Duplicate",dueDate:null,assignedStaffId:null,notes:null},actorId)]);expect(attempts.filter(x=>x.status==="fulfilled")).toHaveLength(1);const order=await db.order.findUniqueOrThrow({where:{quotationId:q.id},include:{items:true,statusHistory:true,quotation:true}});expect(order.orderNumber).toMatch(/^SPH-ORD-\d{6}$/);expect(order.status).toBe("PENDING");expect(order.customerNameSnapshot).toBe("Sample Print Customer");expect(order.items.map(i=>[i.description,i.lineTotal.toFixed(2)])).toEqual([["Business Cards","4000.00"],["Banner Printing","3500.00"]]);expect(order.quotation!.status).toBe("CONVERTED");expect(order.statusHistory).toHaveLength(1);expect(await db.auditLog.count({where:{entityId:{in:[q.id,order.id]},action:{in:["QUOTATION_CONVERTED","ORDER_CREATED"]}}})).toBe(2)});

test("full workflow histories, invoice bridge, advance/balance ledger and duplicate invoice prevention",async()=>{const q=await accepted("0775551235");const o=await convertQuotation({quotationId:q.id,jobName:"Workflow order",dueDate:"2099-12-31",assignedStaffId:null,notes:null},actorId);for(const s of ["DESIGNING","WAITING_APPROVAL","APPROVED","PRINTING","FINISHING","READY","DELIVERED"] as const)await changeOrderStatus(o.id,s,null,{id:actorId,role:"ADMIN"});await expect(changeOrderStatus(o.id,"PRINTING",null,{id:actorId,role:"ADMIN"})).rejects.toThrow();expect(await db.orderStatusHistory.count({where:{orderId:o.id}})).toBe(8);const inv=await createInvoiceFromOrder(o.id,"2000.00",actorId);expect(inv.invoiceNumber).toMatch(/^SPH-INV-\d{6}$/);expect(inv.grandTotal).toBe("7000.00");expect(inv.outstanding).toBe("5000.00");await addInvoicePayment({invoiceId:inv.id,amount:"5000.00",method:"BANK_TRANSFER",reference:`Phase 4 ${run}`},actorId);const saved=await getInvoiceById(inv.id);expect(saved!.orderId).toBe(o.id);expect(saved!.customerPhoneSnapshot).toBe("0775551235");expect(saved!.payments.map(p=>p.amount.toFixed(2))).toEqual(["2000.00","5000.00"]);await expect(createInvoiceFromOrder(o.id,null,actorId)).rejects.toThrow("already has an invoice")});

test("cancellation persists terminal history and due-date fixtures retain source records",async()=>{const q=await accepted("0775551236");const cancelled=await convertQuotation({quotationId:q.id,jobName:`Cancellation fixture ${run}`,dueDate:"2026-09-07",assignedStaffId:null,notes:null},actorId);await changeOrderStatus(cancelled.id,"CANCELLED","Customer cancelled",{id:actorId,role:"ADMIN"});await expect(changeOrderStatus(cancelled.id,"DESIGNING",null,{id:actorId,role:"ADMIN"})).rejects.toThrow();const c=await db.order.findUniqueOrThrow({where:{id:cancelled.id},include:{statusHistory:true}});expect(c.status).toBe("CANCELLED");expect(c.statusHistory.at(-1)?.newStatus).toBe("CANCELLED");for(const [phone,due] of [["0775551237","2026-09-08"],["0775551238","2099-12-31"]] as const){const quote=await accepted(phone);await convertQuotation({quotationId:quote.id,jobName:`Due ${due} ${run}`,dueDate:due,assignedStaffId:null,notes:null},actorId)}expect(await db.order.count({where:{jobName:{in:[`Cancellation fixture ${run}`,`Due 2026-09-08 ${run}`,`Due 2099-12-31 ${run}`]}}})).toBe(3)});

test("database constraints reject invalid item values and preserve history",async()=>{const q=await db.quotation.findFirstOrThrow({where:{notes:`Phase 4 integration ${run}`},include:{items:true,statusHistory:true}});await expect(db.quotationItem.update({where:{id:q.items[0].id},data:{quantity:"0"}})).rejects.toThrow();await expect(db.quotation.delete({where:{id:q.id}})).rejects.toThrow();expect(await db.quotationStatusHistory.count({where:{quotationId:q.id}})).toBeGreaterThan(0)});
