import Link from "next/link";
import type { CashSessionStatus, Prisma } from "@/generated/prisma/client";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { PageHeading } from "@/components/page-heading";
import { StatusBadge } from "@/components/status-badge";
import { cashMovementLabels, expenseCategoryLabels, formatShopDateTime } from "@/domain/phase5";
import { formatMoney } from "@/domain/financial";
import { requirePermission } from "@/lib/auth";
import { db } from "@/lib/db";
import { hasPermission } from "@/lib/permissions";
import { getOpenCashSession } from "@/server/cash-register-service";
import { CashRegisterControls } from "./cash-register-controls";
import { effectiveOperationalStart, getOperationalDataStartAt } from "@/lib/operational-period";

export default async function CashRegisterPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const user = await requirePermission("cash-register:operate"); const [raw, cutoff] = await Promise.all([searchParams, getOperationalDataStartAt()]); const value = (key: string) => typeof raw[key] === "string" ? raw[key] : "";
  const status = (["OPEN", "CLOSED"] as CashSessionStatus[]).includes(value("status") as CashSessionStatus) ? value("status") as CashSessionStatus : undefined;
  const date = /^\d{4}-\d{2}-\d{2}$/.test(value("date")) ? value("date") : "";
  const requestedFrom = date ? new Date(`${date}T00:00:00+05:30`) : undefined; const effectiveFrom = cutoff ? effectiveOperationalStart(requestedFrom ?? new Date(0), cutoff) : requestedFrom;
  const where: Prisma.CashSessionWhereInput = { status, openedAt: effectiveFrom || date ? { gte: effectiveFrom, lte: date ? new Date(`${date}T23:59:59.999+05:30`) : undefined } : undefined };
  const [active, history] = await Promise.all([getOpenCashSession(), db.cashSession.findMany({ where, include: { openedBy: { select: { name: true } }, closedBy: { select: { name: true } } }, orderBy: { openedAt: "desc" }, take: 100 })]);
  const activity = active ? await Promise.all([db.payment.findMany({ where: { cashSessionId: active.session.id }, include: { invoice: { select: { invoiceNumber: true } }, reversal: true }, orderBy: { createdAt: "desc" }, take: 8 }), db.expense.findMany({ where: { cashSessionId: active.session.id }, orderBy: { createdAt: "desc" }, take: 8 }), db.cashMovement.findMany({ where: { cashSessionId: active.session.id }, orderBy: { createdAt: "desc" }, take: 8 })]) : null;
  const summary = active?.summary;
  return <><PageHeading eyebrow="Finance" title="Cash Register" description="Open, reconcile, and close the single physical cash drawer." action={<StatusBadge status={active ? "OPEN" : "CLOSED"} />} />
    {!active ? <Card className="mb-7 grid gap-6 p-6 lg:grid-cols-[1fr_420px]"><div><h2 className="text-2xl font-black">Cash register closed</h2><p className="mt-2 text-slate-500">Open a session before accepting cash invoice payments or recording cash expenses.</p></div><CashRegisterControls allowAdjust={false} /></Card> : <div className="mb-7 grid gap-5 xl:grid-cols-[1fr_420px]"><div className="space-y-5"><Card className="p-6"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">Register open</h2><p className="text-sm text-slate-500">Opened by {active.session.openedBy.name} · {formatShopDateTime(active.session.openedAt)}</p></div><Button asChild variant="secondary"><Link href={`/cash-register/${active.session.id}`}>Session detail</Link></Button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Amount label="Opening Cash" value={summary!.openingCash.toFixed(2)} /><Amount label="Cash Invoice Payments" value={summary!.cashReceipts.toFixed(2)} positive /><Amount label="Cash Expenses" value={summary!.cashExpenses.toFixed(2)} negative /><Amount label="Cash Deposits" value={summary!.cashDeposits.toFixed(2)} positive /><Amount label="Cash Withdrawals" value={summary!.cashWithdrawals.toFixed(2)} negative /><Amount label="Expected Current Cash" value={summary!.expectedCash.toFixed(2)} strong /></div></Card><Card className="p-6"><h2 className="font-black">Recent cash activity</h2><div className="mt-4 space-y-3">{activity?.[0].map((item) => <Activity key={item.id} title={`Payment · ${item.invoice.invoiceNumber}${item.reversal ? " · REVERSED" : ""}`} amount={item.amount.toFixed(2)} at={item.createdAt} />)}{activity?.[1].map((item) => <Activity key={item.id} title={`Expense · ${expenseCategoryLabels[item.category]}${item.status === "VOID" ? " · VOID" : ""}`} amount={`-${item.amount.toFixed(2)}`} at={item.createdAt} />)}{activity?.[2].map((item) => <Activity key={item.id} title={cashMovementLabels[item.type]} amount={`${item.type === "CASH_DEPOSIT" ? "+" : "-"}${item.amount.toFixed(2)}`} at={item.createdAt} />)}{activity && activity.every((items) => items.length === 0) ? <p className="text-slate-500">No cash activity yet.</p> : null}</div></Card></div><Card className="p-5"><CashRegisterControls sessionId={active.session.id} expectedCash={summary!.expectedCash.toFixed(2)} allowAdjust={hasPermission(user.role, "cash-register:adjust")} /></Card></div>}
    <PageHeading eyebrow="History" title="Register sessions" description="Closed sessions retain their recorded reconciliation." /><Card className="mb-5 p-4"><form className="grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><Input type="date" name="date" defaultValue={date} aria-label="Session date" /><select name="status" defaultValue={status ?? ""} className="min-h-12 rounded-xl border border-slate-300 bg-white px-4"><option value="">All statuses</option><option value="OPEN">Open</option><option value="CLOSED">Closed</option></select><Button variant="secondary">Filter</Button></form></Card><Card className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Session</th><th className="p-4">Opened</th><th className="p-4">Opened by</th><th className="p-4">Opening</th><th className="p-4">Closed</th><th className="p-4">Closed by</th><th className="p-4">Expected</th><th className="p-4">Actual</th><th className="p-4">Difference</th><th className="p-4">Status</th></tr></thead><tbody>{history.map((item) => <tr className="border-t" key={item.id}><td className="p-4"><Link className="font-black text-blue-700" href={`/cash-register/${item.id}`}>{item.id.slice(-8).toUpperCase()}</Link></td><td className="p-4">{formatShopDateTime(item.openedAt)}</td><td className="p-4">{item.openedBy.name}</td><td className="p-4">Rs. {item.openingCash.toFixed(2)}</td><td className="p-4">{item.closedAt ? formatShopDateTime(item.closedAt) : "—"}</td><td className="p-4">{item.closedBy?.name ?? "—"}</td><td className="p-4">{item.expectedCash ? `Rs. ${item.expectedCash.toFixed(2)}` : "—"}</td><td className="p-4">{item.actualCash ? `Rs. ${item.actualCash.toFixed(2)}` : "—"}</td><td className="p-4">{item.difference ? `Rs. ${item.difference.toFixed(2)}` : "—"}</td><td className="p-4"><StatusBadge status={item.status} /></td></tr>)}</tbody></table>{history.length === 0 ? <p className="p-10 text-center text-slate-500">No register sessions match these filters.</p> : null}</Card>
  </>;
}

function Amount({ label, value, positive, negative, strong }: { label: string; value: string; positive?: boolean; negative?: boolean; strong?: boolean }) { return <div className={`rounded-xl p-4 ${strong ? "bg-blue-950 text-white" : "bg-slate-50"}`}><p className="text-xs font-black uppercase opacity-70">{label}</p><p className={`mt-1 text-xl font-black ${positive && !strong ? "text-emerald-700" : negative && !strong ? "text-rose-700" : ""}`}>Rs. {formatMoney(value)}</p></div>; }
function Activity({ title, amount, at }: { title: string; amount: string; at: Date }) { return <div className="flex items-center justify-between gap-4 rounded-xl bg-slate-50 p-3"><div><p className="font-bold">{title}</p><p className="text-xs text-slate-500">{formatShopDateTime(at)}</p></div><p className="font-black">Rs. {amount}</p></div>; }
