"use client";

import { useState, useTransition } from "react";
import { Eye, EyeOff, KeyRound, Pencil, ShieldAlert, UserPlus, X } from "lucide-react";
import type { Role, UserStatus } from "@/generated/prisma/client";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { StatusBadge } from "@/components/status-badge";
import { createStaff, resetPassword, updateStaff, type StaffActionState } from "./actions";

type StaffRow = { id: string; name: string; username: string; role: Role; status: UserStatus; createdAt: string; updatedAt: string };
type Dialog = { type: "create" } | { type: "edit" | "password"; staff: StaffRow } | null;
type SelectableRole = "ADMIN" | "STAFF";
const roleOptions: Array<{ value: SelectableRole; label: string }> = [
  { value: "ADMIN", label: "Admin" }, { value: "STAFF", label: "Staff" },
];

export function StaffManagement({ staff, editable, currentUserId }: { staff: StaffRow[]; editable: boolean; currentUserId: string }) {
  const [dialog, setDialog] = useState<Dialog>(null);
  const [message, setMessage] = useState<StaffActionState>({});
  const [pending, startTransition] = useTransition();
  const [showPassword, setShowPassword] = useState(false);
  const [selectedRole, setSelectedRole] = useState<SelectableRole>("STAFF");
  function run(action: () => Promise<StaffActionState>) { setMessage({}); startTransition(async () => { const result = await action(); setMessage(result); if (!result.error) setDialog(null); }); }
  function submitCreate(formData: FormData) { run(() => createStaff({ name: formData.get("name"), username: formData.get("username"), role: formData.get("role"), status: formData.get("status"), password: formData.get("password"), confirmPassword: formData.get("confirmPassword") })); }
  function submitEdit(formData: FormData, row: StaffRow) { const status = String(formData.get("status")); if (row.status === "ACTIVE" && status === "DISABLED" && !window.confirm(`Disable ${row.name}? Their active sessions will be revoked.`)) return; run(() => updateStaff({ id: row.id, name: formData.get("name"), username: formData.get("username"), role: formData.get("role"), status })); }
  function submitPassword(formData: FormData, row: StaffRow) { run(() => resetPassword({ id: row.id, password: formData.get("password"), confirmPassword: formData.get("confirmPassword") })); }
  return <>
    {!editable ? <p className="mb-5 rounded-xl bg-amber-50 p-4 font-semibold text-amber-800">Only an administrator can create or change staff accounts.</p> : null}
    {message.error ? <p role="alert" className="mb-5 rounded-xl bg-rose-50 p-4 font-bold text-rose-700">{message.error}</p> : null}
    {message.success ? <p role="status" className="mb-5 rounded-xl bg-emerald-50 p-4 font-bold text-emerald-700">{message.success}</p> : null}
    {editable ? <form id="add-staff-trigger" onSubmit={(event) => { event.preventDefault(); setSelectedRole("STAFF"); setShowPassword(false); setDialog({ type: "create" }); }} /> : null}
    <Card className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{["Name", "Username", "Role", "Status", "Created", "Actions"].map((label) => <th key={label} className="p-4">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{staff.map((row) => <tr key={row.id}><td className="p-4 font-black text-slate-950">{row.name}{row.id === currentUserId ? <span className="ml-2 text-xs text-blue-700">YOU</span> : null}</td><td className="p-4 font-mono font-semibold">{row.username}</td><td className="p-4">{row.role === "ADMIN" ? "Admin" : "Staff"}</td><td className="p-4"><StatusBadge status={row.status} /></td><td className="p-4">{formatDate(row.createdAt)}</td><td className="p-4">{editable ? <div className="flex gap-2"><Button type="button" size="icon" variant="secondary" aria-label={`Edit ${row.name}`} onClick={() => { setSelectedRole(row.role === "ADMIN" ? "ADMIN" : "STAFF"); setDialog({ type: "edit", staff: row }); }}><Pencil className="size-5" /></Button><Button type="button" size="icon" variant="secondary" aria-label={`Reset password for ${row.name}`} onClick={() => { setShowPassword(false); setDialog({ type: "password", staff: row }); }}><KeyRound className="size-5" /></Button></div> : "Read only"}</td></tr>)}</tbody></table>{!staff.length ? <p className="p-12 text-center text-slate-500">No staff accounts found.</p> : null}</Card>
    {dialog ? <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4" role="presentation"><div role="dialog" aria-modal="true" aria-labelledby="staff-dialog-title" className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between gap-4"><div><h2 id="staff-dialog-title" className="text-2xl font-black">{dialog.type === "create" ? "Add staff" : dialog.type === "edit" ? `Edit ${dialog.staff.name}` : `Reset ${dialog.staff.name}'s password`}</h2><p className="mt-1 text-sm text-slate-500">{dialog.type === "password" ? "The old password will stop working and active sessions will be revoked." : "Use only the approved Startek POS roles."}</p></div><Button type="button" size="icon" variant="ghost" aria-label="Close" disabled={pending} onClick={() => setDialog(null)}><X className="size-5" /></Button></div>
      {dialog.type === "create" ? <form action={submitCreate} className="mt-6 space-y-4"><StaffFields selectedRole={selectedRole} setSelectedRole={setSelectedRole} /><PasswordFields show={showPassword} setShow={setShowPassword} /><label className="block text-sm font-bold">Initial status<select name="status" defaultValue="ACTIVE" className="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white px-4"><option value="ACTIVE">Active</option><option value="DISABLED">Disabled</option></select></label><Button size="lg" className="w-full" disabled={pending}><UserPlus className="size-5" />{pending ? "Creating…" : "Create staff account"}</Button></form> : null}
      {dialog.type === "edit" ? <form action={(formData) => submitEdit(formData, dialog.staff)} className="mt-6 space-y-4"><StaffFields row={dialog.staff} selectedRole={selectedRole} setSelectedRole={setSelectedRole} /><label className="block text-sm font-bold">Account status<select name="status" defaultValue={dialog.staff.status} className="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white px-4"><option value="ACTIVE">Active</option><option value="DISABLED">Disabled</option></select></label><Button size="lg" className="w-full" disabled={pending}>{pending ? "Saving…" : "Save staff changes"}</Button></form> : null}
      {dialog.type === "password" ? <form action={(formData) => submitPassword(formData, dialog.staff)} className="mt-6 space-y-4"><PasswordFields show={showPassword} setShow={setShowPassword} /><Button size="lg" className="w-full" disabled={pending}><KeyRound className="size-5" />{pending ? "Resetting…" : "Reset password"}</Button></form> : null}
      {message.error ? <p role="alert" className="mt-4 rounded-xl bg-rose-50 p-4 font-bold text-rose-700">{message.error}</p> : null}</div></div> : null}
  </>;
}

function StaffFields({ row, selectedRole, setSelectedRole }: { row?: StaffRow; selectedRole: SelectableRole; setSelectedRole: (role: SelectableRole) => void }) { const legacy = row && row.role !== "ADMIN" && row.role !== "STAFF"; return <><Input name="name" defaultValue={row?.name} placeholder="Full name" autoComplete="off" required /><Input name="username" defaultValue={row?.username} placeholder="Username" autoCapitalize="none" autoCorrect="off" spellCheck={false} autoComplete="off" required minLength={3} maxLength={32} /><label className="block text-sm font-bold">Role<select name="role" value={selectedRole} onChange={(event) => setSelectedRole(event.target.value as SelectableRole)} className="mt-2 min-h-12 w-full rounded-xl border border-slate-300 bg-white px-4">{roleOptions.map((role) => <option key={role.value} value={role.value}>{role.label}</option>)}</select></label>{legacy ? <p className="rounded-xl bg-blue-50 p-4 text-sm font-bold text-blue-800">This legacy account is shown as Staff. Saving converts it to the final Staff role and revokes its active sessions.</p> : null}{selectedRole === "ADMIN" ? <p className="flex gap-2 rounded-xl bg-amber-50 p-4 text-sm font-bold text-amber-800"><ShieldAlert className="size-5 shrink-0" />Administrators have full access to staff, settings, backups, and Start Fresh.</p> : null}</>; }
function PasswordFields({ show, setShow }: { show: boolean; setShow: (show: boolean) => void }) { return <div className="space-y-3"><div className="relative"><Input name="password" type={show ? "text" : "password"} placeholder="Temporary password (12+ characters)" autoComplete="new-password" required minLength={12} /><Button type="button" size="icon" variant="ghost" className="absolute right-0 top-0" aria-label={show ? "Hide password" : "Show password"} onClick={() => setShow(!show)}>{show ? <EyeOff className="size-5" /> : <Eye className="size-5" />}</Button></div><Input name="confirmPassword" type={show ? "text" : "password"} placeholder="Confirm temporary password" autoComplete="new-password" required minLength={12} /></div>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-LK", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Colombo" }).format(new Date(value)); }
